version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/community.lazycat.app.netbird.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: netbird

build:
  toolchains: []
  run_buildscript: false

images:
  - id: netbird
    target: service
    service: netbird
    source: docker.io/netbirdio/netbird
    channel: stable
    sort: semver
    tag_regex: '^\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: false
    skip_if_version_exists: false
    retry:
      enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: NetBird
    summary: Published from GitHub Actions
